// Assembles apps/free/dist, the directory you point "Load unpacked" at.
//
// Why a build step exists at all: content scripts are not ES modules. A file
// declared in manifest.content_scripts is executed as a classic script, so it
// cannot import anything. But protocol.js and endpoints.js are needed by both
// the MAIN-world interceptor and the isolated-world bridge, and duplicating
// them is exactly how the two halves of a message channel drift apart.
//
// So: sources are authored as plain ES modules (one concern per file, directly
// testable in Vitest), and this script concatenates each content-script entry
// with its dependencies into one classic IIFE. Dependency lists are written out
// by hand below rather than discovered by parsing imports. Four files do not
// justify a module graph, and an explicit list is one less thing that can
// surprise you.
//
// Everything else (popup, service worker) loads as a real module and is copied
// verbatim.

import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { ICON_SIZES, renderIcon } from './make-icons.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'apps/free/dist');

const CAPTURE = 'packages/capture/src';
const CORE = 'packages/core/src';
const FREE = 'apps/free/src';

// Each content-script entry, in load order. Order is the dependency order.
const BUNDLES = [
  {
    out: 'capture/interceptor.js',
    world: 'MAIN',
    sources: [`${CAPTURE}/protocol.js`, `${CAPTURE}/endpoints.js`, `${CAPTURE}/interceptor.js`],
  },
  {
    out: 'capture/bridge.js',
    world: 'ISOLATED',
    sources: [`${CAPTURE}/protocol.js`, `${CAPTURE}/endpoints.js`, `${CAPTURE}/bridge.js`],
  },
];

// Copied as-is. These load as ES modules and can import each other.
const COPIES = [
  [`${FREE}/popup.html`, 'popup.html'],
  [`${FREE}/popup.css`, 'popup.css'],
  [`${FREE}/popup.js`, 'popup.js'],
  [`${FREE}/service-worker.js`, 'service-worker.js'],
  [`${CAPTURE}/protocol.js`, 'lib/protocol.js'],
  [`${CORE}/summary.js`, 'lib/summary.js'],
  [`${CORE}/trim.js`, 'lib/trim.js'],
  [`${CORE}/strip-html.js`, 'lib/strip-html.js'],
  [`${CORE}/json-span.js`, 'lib/json-span.js'],
  [`${CORE}/ui-numbers.js`, 'lib/ui-numbers.js'],
  [`${CORE}/ai-context.js`, 'lib/ai-context.js'],
  ['apps/free/manifest.json', 'manifest.json'],
];

// ---------------------------------------------------------------- helpers

function read(relative) {
  return readFileSync(join(ROOT, relative), 'utf8');
}

function write(relative, contents) {
  const target = join(OUT, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
}

/**
 * Turn one ES module into a fragment that can live inside a shared IIFE.
 *
 * Deliberately dumb: single-line imports get dropped, a leading `export ` gets
 * removed, and anything else that still looks like module syntax afterwards is
 * a hard error. A bundler that silently half-works on a content script produces
 * a page that mostly loads and an extension that mostly captures, which is a
 * far worse afternoon than a build failure.
 */
function toClassicFragment(relativePath) {
  const lines = read(relativePath).split('\n');
  const kept = [];

  for (const [index, line] of lines.entries()) {
    if (/^import\s/.test(line)) {
      if (!/;?\s*$/.test(line) || (line.includes('{') && !line.includes('}'))) {
        throw new Error(
          `${relativePath}:${index + 1} has a multi-line import. Keep imports on one line: ` +
            'the bundler in tools/build.mjs is intentionally line based.',
        );
      }
      continue;
    }
    kept.push(line.replace(/^export\s+(?=(const|let|var|function|class|async)\b)/, ''));
  }

  const body = kept.join('\n');
  const leftover = body.split('\n').find((line) => /^(import|export)\s/.test(line));
  if (leftover) {
    throw new Error(`${relativePath}: module syntax survived bundling: ${leftover.trim()}`);
  }

  return `// ---- ${relativePath} ----\n${body}`;
}

// ---------------------------------------------------------------- build

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

for (const [from, to] of COPIES) {
  if (!existsSync(join(ROOT, from))) throw new Error(`missing source file: ${from}`);
  write(to, read(from));
}

for (const bundle of BUNDLES) {
  const header = [
    '// Generated by tools/build.mjs. Do not edit.',
    `// ${bundle.world}-world content script, assembled from:`,
    ...bundle.sources.map((s) => `//   ${s}`),
    '',
  ].join('\n');

  const fragments = bundle.sources.map(toClassicFragment).join('\n\n');
  write(bundle.out, `${header}(() => {\n'use strict';\n\n${fragments}\n})();\n`);
}

for (const size of ICON_SIZES) {
  write(`icons/icon-${size}.png`, renderIcon(size));
}

// ---------------------------------------------------------------- assertions
//
// Cheap structural checks. The build is the last place these are free.

const manifest = JSON.parse(read('apps/free/manifest.json'));

if (JSON.stringify(manifest.host_permissions) !== JSON.stringify(['*://*.hubspot.com/*'])) {
  throw new Error('free build host_permissions must be exactly ["*://*.hubspot.com/*"]');
}

const worlds = manifest.content_scripts.map((cs) => cs.world);
if (!worlds.includes('MAIN') || !worlds.includes('ISOLATED')) {
  throw new Error('free build needs one MAIN-world and one ISOLATED-world content script');
}

for (const cs of manifest.content_scripts) {
  if (cs.run_at !== 'document_start') {
    throw new Error(
      'content scripts must run at document_start, or HubSpot captures the original fetch first',
    );
  }
  for (const file of cs.js) {
    if (!existsSync(join(OUT, file))) throw new Error(`manifest references a missing file: ${file}`);
  }
}

// The MAIN-world script has no chrome.* access at all. Referencing it there is
// not a runtime warning, it is a thrown ReferenceError inside a customer's
// workflow editor.
// Comments stripped first: this file and protocol.js both talk about chrome.*
// in prose, and a check that cannot tell prose from code is a check nobody
// trusts for long.
const stripComments = (source) =>
  source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');

const mainBundle = stripComments(readFileSync(join(OUT, 'capture/interceptor.js'), 'utf8'));
if (/\bchrome\./.test(mainBundle)) {
  throw new Error('MAIN-world bundle references chrome.*; it runs in the page world and has none');
}

console.log(`built ${OUT}`);
for (const bundle of BUNDLES) {
  const bytes = readFileSync(join(OUT, bundle.out)).length;
  console.log(`  ${bundle.out.padEnd(24)} ${String(bytes).padStart(6)} bytes  (${bundle.world})`);
}
